[package]
name = "wark"
description = """
    A yet deployment tool for mglawica stack
"""
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["deplay", "containers", "vagga"]
categories = ["command-line-utilities"]
homepage = "https://github.com/tailhook/wark"
documentation = "https://github.com/tailhook/wark"
version = "0.1.0"
authors = ["paul@colomiets.name"]

[dependencies]
abstract-ns = "0.4.1"
ns-router = "0.1.1"
ns-std-threaded = "0.3.0"
tk-http = { version="0.3.5", default-features=false }
failure = "0.1.1"
argparse = "0.2.1"
url = "1.5.1"
futures = "0.1.16"
tokio-core = "0.1.10"
env_logger = "0.4.3"
tk-easyloop =  "0.1.1"
